### ISSUE TITLE
Allow for French YAML option

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/csasdowntex#1]
Rowan has a French translation function for figures that may be worth adopting/adapting at some point

Just came across Rowan's `linguaFranc()` in here: https://github.com/pbs-software/pbs-tools/blob/master/PBStools/R/M01_Utility.r

Just flagging it in case we want to go down the route of automatically producing French figures - maybe he has a method for that already.

**Comment by ricardd** [comment]
@seananderson what is involved in terms of making the csasdown package truly bilingual? When one puts French as the language in the YAML header, it should produce a French document, so how will the LaTeX style file be handled? In the csas-style-sr from @grinnellm we have 2 separate style files, but it seems that we could instead use a flag to specify which language to use. Feel free to put your thoughts as a reply and we can go from there.

**Comment by seananderson** [comment]
We can either maintain `sr.sty` and `st-french.sty` etc. or we can have one `sr.sty` and a bunch of if else statements in it. Not sure which would be easier to maintain. Maybe the if-else version? 

Yes, it probably makes sense to have a flag for the language. The current idea was to use `sr` or `sr-french` with the `type` flag. I'm now realizing that we might want different default `index.Rmd` files and example .Rmd files so instead of having a `type` flag (1) you'd be advised to decide when you initialize the report and (2) the appropriate rendering and .tex / .sty file would be called by the flag `output:  csasdown::resdoc_pdf` vs. `csasdown::sr_pdf` etc.

If we passed a flag of `language: english` or `language: french`... or perhaps less error-prone `french: true` or `french: false`, we could pass that through to the .tex and .sty and use appropriate if-else statements to print the necessary text.

So far I've just been talking about the French and English text on the title pages and for things like section and appendix. If we want a way to maintain separate .Rmd content files that optionally get collated based on some YAML flag, that's a whole other thing. The simple solution would be to just have 2 versions of the `_bookdown.yml` file that collate the `-en` or `-fr` .Rmd files. The user could temporarily rename one of them and recompile. Getting fancier, it may be possible to somehow to pick `_bookdown_en.yml` or `_bookdown_fr.yml` based on a YAML flag. That will depend on how bookdown has been written and whether we can hijack that.

**Comment by seananderson** [comment]
After the experience integrating the French version for the science response yesterday, I think a reasonable solution would be to add an argument to each function (`resdoc_pdf()`, `sr_pdf()`, ...) that is `french = TRUE/FALSE`. Those can easily be passed through the YAML. Then inside the function we call the appropriate .tex or .docx file for French or English. It's true that we end up with some duplication of files, but (1) the duplicated files have mostly already been finished and so it saves time to not have to redo this and (2) they are very rarely going to need to be updated so is not a big deal to make the same change in multiple places very occasionally.

**Comment by ricardd** [comment]
@seananderson , I am working on the French version of a ResDoc now and agree with your proposed solution. It is fine to have 2 separate folders, one for the English version and one for the French version.

Let me see what I can modify in the csasdown package and I will create a pull request with my changes.

**Comment by ricardd** [comment]
closing this issue, see pull request #34
