### ISSUE TITLE
Make title bookmark uppercase

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#105]
I added the title to the PDF bookmarks, which is required by CSAS (046df44c088f8fba9050c0066f969d658d01ba8c, 9194ac0ab5983f6293304a038b834462c84bd70a, and b07424dfe8a427c329ef1374d184d687ba6b6622). It looks funny I know, but the title is supposed to be the lowest level bookmark, and the others (i.e., sections) follow from that. However, the title bookmark needs to be uppercase so I tried to wrap it in `\MakeTextUppercase`. But [that command doesn't work well with `hyperref`](https://tex.stackexchange.com/questions/396367/lowercase-toc-with-memoir-and-hyperref). I have a feeling the solution might use `\expandafter` [like this](https://tex.stackexchange.com/questions/35680/uppercase-in-newcommand), but I can't get it to work yet.

**Comment by cgrandin** [comment]
@grinnellm I'm trying to clean up some of the issues and wonder what this is about? Can we close it? Thanks

**Comment by grinnellm** [comment]
It's not resolved, so maybe keep it open?

**Comment by grinnellm** [comment]
Looking at this again. I thought there would be an easy fix, but maybe not. In the bookmarks on the left, the title part ("Stock status update...") should be uppercase. (But not in the "Correct citation for this publication" part.)
![image](https://user-images.githubusercontent.com/25674027/110019668-94bd9080-7cdd-11eb-9bad-9d063c4074e9.png)

**Comment by andrew-edwards** [comment]
Those changes in 796975d gave me an error:
```
! Undefined control sequence.
l.22 \ExplSyntaxOn
```
that I'm fixing in the commit below (to be pushed shortly).

**Comment by andrew-edwards** [comment]
@grinnellm - I haven't fully tested it (don't have a full SR on the go). But I think I the `\newcommand\textupper{}` I had to include in the last commit (to avoid errors) may have undone the capitalisation in the bookmarks? Any chance you could run your sr if you have a chance?

With `\newcommand\textupper{}` commented out (I added it in the above commit), I get:
```
! Undefined control sequence.
\rdTitleUpper ->\textupper 
                           {\rdTitle {}}
l.123 \bookmark[dest=PageOne]{\rdTitleUpper{}}
```
and these Germans said to add that line in (though I had to put after the `\ExplSyntaxOff`, not before): https://tex.stackexchange.com/questions/548437/how-can-i-use-expl3-text-uppercase-for-hyperref-bookmarks-with-german-umlauts
 
I originally installed latex using ProText (which installs MikTex, basically all the latex packages), so rather than tinytex.

Reopening in case it's still an issue.

**Comment by seananderson** [comment]
You can test with the unit tests. Run the first ~22 lines of https://github.com/pbs-assess/csasdown/blob/master/tests/testthat/test-sr.R in the console and look at the PDF. `system("open .")` on a Mac, something similar on Windows.

The last commit fails the unit tests (on the SR French PDF), but I haven't dug into why and I'm not sure it's actually because of the last commit. https://github.com/pbs-assess/csasdown/actions/runs/1699133881

**Comment by seananderson** [comment]
I had to remove the `\newcommand\textupper{}` to avoid an error about it being already defined. With that, SR PDFs build in the unit tests with all-caps titles with the latest tinytex install.

**Comment by andrew-edwards** [comment]
Thanks. I just saw that it failed. I'll just keep what I have locally for now for the SR.

Wouldn't a simpler option have been to just insist that people write the title in all caps?

**Comment by grinnellm** [comment]
Simpler?!
This is working for me.. title bookmark is uppercase and I'm not getting any errors.

**Comment by cgrandin** [comment]
@andrew-edwards Can we close this?

**Comment by andrew-edwards** [comment]
Okay to close. I'll look at again sometime - for now I just won't update csasdown locally. (Think it will get resolved if I switch to tinyTex, which I'll before next hake assessment anyway).
