### ISSUE TITLE
The french technical report doesn't mention the right type of report.

### ISSUE THREAD

**Issue by jordanoplante** [pbs-assess/csasdowntex#113]
Hey all!

Thanks for the fantastic work done so far! I'm trying these days to put together a french tech report with your package and found out several little issues that I will be mentionning in the next days.

First of, I think we should replace these in the tech-report-french.sty file:
- line 253: "Rapp. manus. can. sci. halieut. aquat." should read as "Rapp. tech. can. sci. halieut. aquat. "
- lines  285 & 352: "manuscrit" should read as "technique"

How do you correct these as the .sty file is overwritten each time I knit the index.Rmd file?

**Comment by seananderson** [comment]
Changes to the .sty files need to be made in the R package because the version from the package overwrites the local copy each time you compile. You are welcome to make the change and make a pull request. Alternatively, we’d be happy to make the changes for you. I’ll let @ricardd chime in on the content. I believe he’s worked the most with the French tech report.

**Comment by jordanoplante** [comment]
Thanks @seananderson. I'll look at the mechanics of doing this with Daniel next week if he's available. I'm quite new to all this git stuff

**Comment by ricardd** [comment]
@jordanoplante I just saw this, sorry for not chiming in earlier, it seems all resolved now.
