### ISSUE TITLE
Section header is not on the same page as a table created in landscape mode.

### ISSUE THREAD

**Issue by jordanoplante** [pbs-assess/csasdowntex#118]
I created a section heading for a bunch of tables, and unfortunately, the first table is in landscape mode. This means that the section title is not on the same page as the first table even if there would be ample space

Example:

\clearpage
## Tables
```{r widelong, results = "asis"}
yrs <- 1:45
ages <- 1:15
widelong <- matrix(round(rnorm(length(yrs) * length(ages), 20), 4),
  nr = length(yrs),
  nc = length(ages),
  dimnames = list(year = yrs, age = ages))
widelong_df <- data.frame(cbind(yrs, widelong))

# In landscape tables, you can change the font size if the table
# is too large and overlaps the header and footer lines.
csasdown::csas_table(widelong_df,
  col.names = c("Year", as.character(ages)),
  caption = "A long and wide table",
  format = "latex",
  landscape = TRUE,
  font_size = 8)
```
\clearpage

Someone knows a workaround?

**Comment by seananderson** [comment]
I'm not sure. I've tried to avoid landscape pages like the plague. Maybe somebody else who has worked with them could chime in?

**Comment by ricardd** [comment]
@jordanoplante perhaps see issue #31 ?

**Comment by obradovichs** [comment]
@maburton created this workaround for our CSAS Res Doc. This fix is written for an appendix that is one in a series of appendices. @maburton also modified the sty file for our Res Doc to change the position of the header/footer lines and page number, as well as the orientation of the page in the PDF. See Issue #156.

`\clearpage

\begin{landscapepage}
\chapter{Density Tables} \label{app:dentables}

```{r my table}
table code
```
\end{landscapepage}
\clearpage`

**Comment by maburton** [comment]
@obradovichs  and I fixed this on rotated pages which requires using the \begin{landscapepage} environment. So this work around involves my answer in issue #156 and changes to the .sty file. 
But you should then be able to create the new section using latex syntax rather than rmarkdown syntax. So if you wanted a new chapter it would be \chapter (equivalent to "# New Chapter" in rmarkdown) , if you wanted a section within a chapter it would be \section (equivalent to "## New Section" in rmarkdown), and if you wanted a section within a section it would be \subsection (equivalent to "### New Subsection" in rmarkdown).

As per the explanation in issue #156 to rotate the pages you have to keep landscape = False in csas_table since we will be rotating the page rather than rotating the table. And I added a label since that has to be in latex format as well but you can just call it normally within the document.

You can then code it such that
\clearpage
\begin{landscapepage}
\section{Tables} \label{section:table}
```{r tables}
yrs <- 1:45
ages <- 1:15
widelong <- matrix(round(rnorm(length(yrs) * length(ages), 20), 4),
  nr = length(yrs),
  nc = length(ages),
  dimnames = list(year = yrs, age = ages))
widelong_df <- data.frame(cbind(yrs, widelong))

# In landscape tables, you can change the font size if the table
# is too large and overlaps the header and footer lines.
csasdown::csas_table(widelong_df,
  col.names = c("Year", as.character(ages)),
  caption = "A long and wide table",
  format = "latex",
  landscape = FALSE,
  font_size = 8)
  ```
  \end{landscapepage}
  \clearpage
  
  Hope that helps

**Comment by cgrandin** [comment]
This and all landscape table stuff is now addressed in the Wiki here: https://github.com/pbs-assess/csasdown/wiki/How-to-make-landscape-tables
@jordanoplante, @maburton , @seananderson , @ricardd, @jaclyncleary , @robynforrest , @brendanmichaelconnors, @CamFreshwater, @obradovichs, @grinnellm, @andrew-edwards
Please let anyone else know that has had troubles with this. Thanks

**Comment by grinnellm** [comment]
I did something for landscape tables in the SR using `\turn`.
