### ISSUE TITLE
Adding footnotes and references to tables

### ISSUE THREAD

**Issue by carrieholt** [pbs-assess/csasdowntex#129]
I'd like to add footnotes with references, or simply references to tables, but the standard syntax for references does not seem to work within tables.
I tried using  add_footnote() in kable with a reference in the footnote unsuccessfully.  I ended up doing the footnotes manually in the text, but would eventually like to find a better way.

**Comment by seananderson** [comment]
References to citation, figures, or other tables can work within tables, but might require some escaping. Do you mean in the caption or the table cells?

**Comment by carrieholt** [comment]
In the table cells.

**Comment by seananderson** [comment]
Does this not work for you?

```r
d <- data.frame(ref = "[@edwards2013]")
csasdown::csas_table(d)
```

<img width="197" alt="image" src="https://user-images.githubusercontent.com/19349/82736184-74878c80-9cdc-11ea-837e-e4a6a42933f6.png">

I made that test in a fresh resdoc template.

If you're reading from a .csv you may need some backslashes.

Otherwise, it's possible it's reverted to `csasdown::csas_table(type = "latex")`. Find the relevant code in `_book/resdoc.tex` (or `_book/sr.tex` etc.) and paste it here.

**Comment by carrieholt** [comment]
Yes, it is a latex issue. When I cut and paste the code from *.tex file, with an extra backslash, the citation looks nice in the table, but the reference is not added to the reference list even though edwards2013 is in my *.bib.

`d <- data.frame("Edwards et al. \\hyperlink{ref-edwards2013}{2014}"); csas_table(d, format="latex")`

**Comment by seananderson** [comment]
Does it work if you write it out as in my example? Try adding `format = "pandoc"`:

```r
d <- data.frame(ref = "[@edwards2013]")
csasdown::csas_table(d, format = "pandoc")
```

This:

```r
d <- data.frame("Edwards et al. \\hyperlink{ref-edwards2013}{2014}")
csas_table(d, format="latex")
```

will not work because `Edwards et al. \\hyperlink{ref-edwards2013}{2014}` isn't a Pandoc citation (although that will work as a hack as long as `[@edwards2013]` is cited elsewhere or in `nocite` in the index.Rmd YAML header).

**Comment by seananderson** [comment]
It just occurred to me based on what you posted that maybe you didn't put the R code into an R chunk? I.e. it needs to look like this:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/19349/83335107-474c5880-a25f-11ea-9421-7544f35979bf.png">

**Comment by carrieholt** [comment]
Yes, it was in an R chunk. The trouble is the format="latex", and getting the right code to specify the reference, since the standard @edwards2013 doesn't work.

**Comment by carrieholt** [comment]
Sorry, I just say your comment above the most recent comment. Yes, I will try format=pandoc. Thanks!

**Comment by carrieholt** [comment]
Many thanks. That does work, but messes up my long multi-row tables with text wrapping, formatted for latex. I will stick with my hard-coded references for now, but next time will try format="pandoc" from the beginning when formatting a multi-row table.
