### ISSUE TITLE
Updates to Technical Report cover, explanatory, and colophon pages

### ISSUE THREAD

**Issue by carrieholt** [pbs-assess/csasdowntex#146]
I think the Publications office has updated these. Is it possible to updated these on the csasdown template?
This is the email I received when I tried to submit my pdf. The template online differs slightly from that in csasdown for Technical Reports.

"There are some corrections that need to be made before the report can be published:
-	The cover page and explanatory material page should be created using the templates available on the library’s intranet site. Please recreate the cover page using the template, and please replace the explanatory material page with the template, ensuring that the formatting of the templates is preserved when the pages are inserted into the report. Appendix 3 of the Guide for the Production of Fisheries and Oceans Canada Science Report Series has instructions for how to insert a cover page created in the template into a report. You can find links to the guide and templates on the library’s intranet site [here](http://intra.dfo-mpo.gc.ca/intracom/report/template/index_e.htm).
-	On page ii, there should not be a space before the “E-PDF” in the Cat. No. [colophon page]"

**Comment by seananderson** [comment]
Sorry, just getting to this now. I pushed a fix for the space before E-PDF.

We can adapt the cover page again to match (they want a colour logo now!?), although in the short term, I wonder if it would be fastest for you to just fill in that .doc file and replace the first page with their page in a PDF editor. Same for the 2nd page for now.

Usually, they're fairly relaxed about the exact formatting of the cover page (and document) and past tech reports reflect a variety of styles.

That 2nd page is going to be tough to replicate if they insist it be identical including different indentation and a different font than the rest of the document. @cgrandin, I wonder if it would be easiest for us just to insert their 2nd page directly as a PDF page using something like: https://tex.stackexchange.com/a/164778

**Comment by carrieholt** [comment]
Thanks. Will do.

**Comment by SOLV-Code** [comment]
We used the updated version that fixed the space before e-pdf (as per #146) and merged in the new cover page and inside cover using a pdf generated from the new library word template.

However, now the page numbers in the citation on the colophon page are wrong, as well as the page numbers for English and French abstracts.

Not an urgent fix, because I will just correct it using a pdf editor, but something to be aware of. If this is not happening for anybody else, what could be causing it for this particular report?

**Comment by seananderson** [comment]
Are the page numbers in the citation on the colophon page wrong because of merging in the cover page and inside cover or are they just always wrong?

**Comment by SOLV-Code** [comment]
Rapid response!
They are wrong right after knitting, before the merge. I actually don't know if this is new or not. They just noticed it in this last version in the library.

Not sure if this helps, but we have a *very long* table of contents.

This [just-published res doc](http://waves-vagues.dfo-mpo.gc.ca/Library/40889385.pdf) has the same page number for the front matter (*v*) as the knitted version of our report. In their case it is correct, because the TOC is only 1 page. Then the english and french abstracts are pages *iv* and *v*.  In our case these should be *xiii* in the citation, and *xii* and *xiii* for the abstracts in the TOC. Maybe *iv* and *v* are hard-wired in there?

One more thing:  deleting the original cover and inside cover in [smallpdf.com](smallpdf.com) messes up the hyperlinks in the TOC. They still work, but now points to 2 pages behind where it's supposed to.  However, this did not happen with whatever tool they used to fix [this one](http://waves-vagues.dfo-mpo.gc.ca/Library/40889385.pdf). Just a heads up to watch out for it, while this temporary fix is needed...

**Comment by seananderson** [comment]
@carrieholt what software did you use to switch out the first 2 pages without breaking the table of contents?

**Comment by seananderson** [comment]
I've added a solution for this. With a new Tech Report, there will be the .docx files `tech-report-cover.docx` and `tech-report-cover-french.docx` in the main report folder. Edit one of these, save as a PDF, and they will be spliced in on the fly. If you need them for an existing report, see [here](https://github.com/pbs-assess/csasdown/tree/master/inst/rmarkdown/templates/techreport/skeleton). That's the first page. The 2nd page has been fixed too and should work automatically.

![image](https://user-images.githubusercontent.com/19349/94330423-5a570700-ff79-11ea-9153-1c5e8f6e7d3a.png)

**Comment by carrieholt** [comment]
FYI, I used Foxit Phantom
