### ISSUE TITLE
Fix landscape tables in resdocs using a fix made my Matt for SRs

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#156]
This was a request made by @obradovichs. The header and footer lines on landscape pages currently remain in portrait orientation, this fix will move the lines to landscape along with the rest of the page.

This is what Matt did in the SR code:
https://github.com/pbs-assess/csasdown/blob/09c43dcb202b0b2ecd0285eea85510e7962a1d21/inst/csas-style/sr.sty#L597

**Comment by maburton** [comment]
I have a solution that solves some issues for resdocs. I wasn't able to get Matt's SR code to work for resdoc but I found another solution using the other landscape code in the sr.sty file. 

I found that to get the page rotation to work I had to set csasdown::csas_table(landscape = FALSE). I also had to put \begin{landscapepage} before the table and \end{landscapepage} after as well to get it to work.

This code turns the page using pdflscape instead of lscape at line 331 of res-doc.sty.
I also changed "\thispagestyle" to "\pagestyle" at line 315 to try to get the style applied to multiple pages in a multipage table, but currently this results in the first page being correct and the second page having no header or footer. This is not an issue for single page tables.

**Comment by maburton** [comment]
It won't seem to let me attach it as a file. So here is the code. If someone could help me figure out how to get the header and footer to work on a multi page table that would be great.

%% res-doc.sty - Unoffocial LaTeX style file for Canadian
%%  Science Advisory Secretariat Research Documents.

\usepackage{tabularx}

%% ------------------------------------------------------------------------------
%% Use the resDoc.bst file for bibliography style.
\usepackage{natbib}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Load hyperlink package and set up link colors
\usepackage[breaklinks=true,
            bookmarksopen=true,
            bookmarksdepth=3]
           {hyperref}
\hypersetup{colorlinks,
            plainpages=true,
            linkcolor=black,
            citecolor=black,
            urlcolor=blue,
            bookmarksopen=true,
            bookmarksopenlevel=1}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Set up numbering of bookmarks in the final pdf
\usepackage{bookmark}
\bookmarksetup{numbered}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% For fleqn, which aligns equations
\usepackage{nccmath}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% If you want to show line numbers in the document
\usepackage[running]
           {lineno}

%% Page margins
\usepackage[top=1in,
            bottom=1in,
            left=1in,
            right=1in]
           {geometry}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% To add in headers and footers
\usepackage{fancyhdr}
\usepackage[format=plain,
            indention=0cm,
            labelsep=period,
            font={small, it},
            justification=raggedright,
            singlelinecheck=false]
           {caption}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Table of Contents
\usepackage{tocloft}
%% Set dot spacing size in TOC for each section
\renewcommand{\cftchapdotsep}{1}
\renewcommand{\cftsecdotsep}{1}
\renewcommand{\cftsubsecdotsep}{1}
\renewcommand{\cftsubsubsecdotsep}{1}
%% Enable dots for chapters in the TOC
\renewcommand{\cftchapleader}{\cftdotfill{\cftchapdotsep}}
%% Un-bold the chapter text in the TOC
\renewcommand{\cftchapfont}{\mdseries}
%% Un-bold the chapter page numbers in the TOC
\renewcommand{\cftchappagefont}{\mdseries}
%% Make the chapter entries the same indentation as the sections
%%  (entry, indent, numWidth)
%% See the tocloft documentation to get these values
\cftsetindents{chapter}{1.5em}{2.3em}
%% Set vertical spacing between entries in TOC
\setlength{\cftbeforechapskip}{5pt}
\setlength{\cftbeforesecskip}{5pt}
\setlength{\cftbeforesubsecskip}{5pt}
\setlength{\cftbeforesubsubsecskip}{5pt}
%% Remove space between the Table of contents title and it's content.
\setlength\cftaftertoctitleskip{6pt}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% To have less whitespace after Table caption. 'above' tells it to put the
%%  skip after caption, but you may still need to have the caption before the
%%  table in .tex
\captionsetup[table]{position=above, skip=5pt}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% If you are including EPS files these are necessary
%% For epsfbox
\usepackage{epsfig}
%% for \includegraphics (eps and others)
\usepackage{graphicx}
\DeclareGraphicsExtensions{.pdf,.png,.jpg}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% For ragged right and bottom margins (yes, ugly, but that's the rules, which
%%  of course exist because right justified in Word always looks so bad)
\RequirePackage{ragged2e}
\RequirePackage{microtype}
% Default is 50 (lots of hyphenation); bigger values penalize hyphenation more; make it huge to completely avoid them;
% 1200 is my guess at a reasonable compromise:
\hyphenpenalty=1200 % https://tex.stackexchange.com/questions/291685/minimize-hyphenations-with-ragged2e
\RaggedRight
\raggedbottom
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Paragraph text settings
%% To not indent paragraphs.
\setlength\parindent{0pt}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Contraction after fake subsubheading
\def\headc{\vspace{-2ex}}
%% Fake subsubsubheading
\def\subsubsub#1{\vspace{1ex} \noindent {\underline{#1}} \vspace{1ex}}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Commands which match the CSAS template guide for sections, subsections,
%%  subsubsections, and chapters. There is also a command for appsection, which
%%  left-justifies sections in the appendices as they are now below chapters.
%% There are also macros to set up the table of contents, main body, and
%%  appendices correctly for CSAS.
%% The bibliography is renamed REFERENCES as well.
\makeatletter
%% These two commands are required to use Arial for the document.
% \renewcommand{\rmdefault}{phv}
% \renewcommand{\sfdefault}{phv}

\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}

%% Useful shortcuts for equations
\newcommand{\eb}{\begin{eqnarray}}
\newcommand{\ee}{\end{eqnarray}}

\newcommand{\nonumsection}{\@startsection
{section}{1}{0mm}                 %% name, level, indent
{-3.5ex \@plus -1ex \@minus -.2ex}%% beforeskip
{2.3ex \@plus.2ex}                %% afterskip
{\centering\normalfont\large\bfseries\MakeUppercase}}

\renewcommand{\section}{\@startsection
{section}{1}{0mm}
{-3.5ex \@plus -1ex \@minus -.2ex}
{2.3ex \@plus.2ex}
{\centering\normalfont\large\bfseries\MakeUppercase}}

\renewcommand{\subsection}{\@startsection
{subsection}{2}{0mm}
{-3.25ex plus -1ex minus  -.2ex}{1.5ex plus .2ex}
%% {1ex}{0.1ex plus -2ex}
{\normalfont\bf\MakeUppercase}}

\renewcommand{\subsubsection}{\@startsection
{subsubsection}{3}{0mm}
{-2ex plus -1ex minus -.2ex}{1.5ex plus .2ex}
{\normalfont\bf}}

\renewcommand{\chapter}{\@startsection
{chapter}{1}{0mm}
{-3.5ex \@plus -1ex \@minus -.2ex}
{2.3ex \@plus.2ex}
{\centering\normalfont\large\bfseries\MakeUppercase}}

%% Section headings in appendices must be left-justified not centered;
%%  this is same as \section above but without \centering.
%%  \section is now redefined in \Appendices command, so \section can
%%  be used as normal (or use \appsection) in appendices.
\newcommand{\appsection}{\@startsection
{section}{1}{0mm}                 %% name, level, indent
{-3.5ex \@plus -1ex \@minus -.2ex}%% beforeskip
{2.3ex \@plus.2ex}                %% afterskip
{\normalfont\large\bfseries\MakeUppercase}} %% style

\newcommand\TableOfContents{
  \thispagestyle{fancyplain}
  \pagenumbering{roman}
  %% TOC is required by CSAS to be on page iii.
  \setcounter{page}{3}
  \renewcommand{\contentsname}{\bf \large \vspace{-20mm} TABLE OF CONTENTS}
  \addtocontents{toc}{\protect\thispagestyle{fancy}}
  \begin{center}
    \tableofcontents
  \end{center}
  \newpage
  %% To number subsubheadings
  \setcounter{secnumdepth}{5}
}

\newcommand\Citation[1]{
  %% Start citation indentation
  \leftskip=3em
  \parindent=-3em
  {\bf Correct citation for this publication:}

  #1

  %% End citation indentation
  \leftskip=0em
  \parindent=-0em
}

\newcommand\Main{
  %% To number the main document sections, tables, etc.
  %%  as 1.1, 1.2, etc.
  \renewcommand{\thesection}{\arabic{section}}
  \renewcommand{\thesubsection}{\arabic{section}.\arabic{subsection}}
  \renewcommand{\thesubsubsection}{\arabic{section}.\arabic{subsection}.\arabic{subsubsection}}
  \renewcommand{\thetable}{\arabic{table}}
  \renewcommand{\thefigure}{\arabic{figure}}
  \renewcommand{\theequation}{\arabic{equation}}
}

\newcommand\Appendices{
  %% Start appendices. Sets up numbering for appendix sections
  %%  and their contents (tables, figures) to look like:
  %%  A.1, A.2, A.1.2
  \appendix
  %% Always start a new page for appendices
  \newpage
  \renewcommand{\thesection}{\thechapter.\arabic{section}}
  \renewcommand{\thesubsection}{\thechapter.\arabic{section}.\arabic{subsection}}
  \renewcommand{\thesubsubsection}{\thechapter.\arabic{section}.\arabic{subsection}.\arabic{subsubsection}}
  \renewcommand{\thetable}{\thechapter.\arabic{table}}
  \renewcommand{\thefigure}{\thechapter.\arabic{figure}}
  \renewcommand{\theequation}{\thechapter.\arabic{equation}}
  %% Set up Appendices in the TOC to not show subsections
  \addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
  %% Set up first Appendix heading value
  \setcounter{chapter}{0}
  %% Section headings now use \appsection command
  \renewcommand{\section}{\appsection}
}

%% Changes the name of the bibliography to REFERENCES.
\renewcommand{\bibname}{REFERENCES}
%% To make REFERENCES a section and then number it
\renewcommand{\bibsection}{\section{\bibname}}

%% Makes figures stick to the top of the page. i.e. if there is a single figure
%%  on a page, it will be placed in the center. This forces it to stick
%%  to the top.
\setlength\@fptop{0pt}

%% From hake.sty:
%% Change default options for float rules for figure and tables, from:
%%  http://www.tex.ac.uk/FAQ-floats.html  . Also see p55 of
%%  http://tug.ctan.org/tex-archive/info/epslatex/english/epslatex.pdf
%%  Allows a larger percentage of a page to be a figure than in the defaults
\renewcommand{\topfraction}{.85}
\renewcommand{\bottomfraction}{.7}
\renewcommand{\textfraction}{.15}
\renewcommand{\floatpagefraction}{.66}
\renewcommand{\dbltopfraction}{.66}
\renewcommand{\dblfloatpagefraction}{.66}
\setcounter{topnumber}{9}
\setcounter{bottomnumber}{9}
\setcounter{totalnumber}{20}
\setcounter{dbltopnumber}{9}

%% Make all minipages be ragged right like the main text
\let\@minipagerestore=\raggedright

%% Make appendices have entry in the table of contents
\newcommand{\starredchapter}[1]{
  \clearpage
  %% Make spacing between top of page and heading less.
  \vspace*{-40\p@}
  \phantomsection
  %% Add the appendix name to the table of contents.
  \addcontentsline{toc}{chapter}{#1}\chapter*{#1}
}

%% Make English abstract have entry in the table of contents
\newcommand{\abstract}{
  \clearpage
  %% Make spacing between top of page and heading less.
  \vspace*{-40\p@}
  \phantomsection
  %% Add the appendix name to the table of contents.
  \addcontentsline{toc}{section}{ABSTRACT}\nonumsection*{ABSTRACT}
}

%% Make French abstract have entry in the table of contents
\newcommand{\frenchabstract}[1]{
  \clearpage
  %% Make spacing between top of page and heading less.
  \vspace*{-30\p@}
  \phantomsection
  \begin{center}
    \Large \textbf{#1}
  \end{center}
  \vspace{-6mm}
  %% Add the appendix name to the table of contents.
  \addcontentsline{toc}{section}{R\'ESUM\'E}\nonumsection*{R\'ESUM\'E}
}

%% Make a landscape page properly, with the page numbers and bars rotated to
%%  be along the long side for ease of reading in a PDF viewer.
\newenvironment{landscapepage}[1]{
  \newgeometry{hmargin=1in,vmargin=1in}
  \pagestyle{csaplscape} % changed from "thispagestyle"
  \begin{landscape}
    \centering
    #1
}{
  \end{landscape}
  \restoregeometry
  \clearpage
  }

\makeatother
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% For landscape pages in CSAS documents
\usepackage{pdflscape} %change to pdflscape from lscape
%\usepackage{lscape}
\usepackage[absolute]{textpos}
\setlength{\TPHorizModule}
  {8.5in}
\setlength{\TPVertModule}
  {11.0in}
\fancypagestyle{csaplscape}{
  %% The argument is the left footer text
  %% clear all header and footer fields
  \fancyhf{}
  \fancyfoot{}
  %% Make the footers appear in landscape mode
  %% The 25pt in the first line adjusts the height (in landscape mode)
  %%  and the 90 rotates the footer name. The \footskip+0.0 makes it align
  %%  with the footer bar, like the pages in portrait mode do.
  %% Left footer:
  %% \fancyfoot[L]{\makebox[\textwidth+25pt][r]{
  %%    \smash{\raisebox{\dimexpr\footskip+0.0\textheight}{\rotatebox{90}{\fishname}}}}}
  %% Right footer - uncomment and change DRAFT to whatever the value for the right
  %%  footer is and the 1.3 to fit it. This is a hack, no time to figure it out.
  %% \fancyfoot[R]{\makebox[\textwidth+25pt][r]{
  %%    \smash{\raisebox{\dimexpr\footskip+1.3\textheight}{\rotatebox{90}{DRAFT}}}}}
  \begin{textblock}
    {1}(0.1,0.0909)
    {\rotatebox{90}
      {\rule{9in}{0.25pt}}
    }
  \end{textblock}
  \begin{textblock}
    {1}(0.9,0.0909)
    {\rotatebox{90}
      {\rule{9in}{0.25pt}}
    }
  \end{textblock}
  \begin{textblock}
    {0.05}(0.925,0.5)
    {\rotatebox{90}
      {\thepage}
    }
  \end{textblock}
  %% Get rid of lines along sides of landscape page
  \renewcommand{\headrulewidth}
    {0pt}
  \renewcommand{\footrulewidth}
    {0pt}
}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Defines the header and footer rules for a CSAS paper.
\pagestyle{fancy}
\renewcommand{\footrulewidth}{0.4pt}
\renewcommand{\headrulewidth}{0.4pt}
\fancypagestyle{csapfancy}{%%
  %% \fancyhead[L]{}%%{DRAFT -- Non-citable working paper}
  %% \fancyhead[R]{}%%{CSAP WP2016zzzxx}
  %% \fancyfoot[L]{}%%{Appendix \thechapter -- Model Results}
  %% \fancyfoot[R]{}%%{\Sexpr{paste0(sppname," (",area.name,")")}}
  \fancyfoot[C]{\thepage}
  \renewcommand{\footrulewidth}{0.4pt}
  \renewcommand{\headrulewidth}{0.4pt}
}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Indentation, types, and numbering of enumerated or bullet-point lists
\usepackage{enumerate}
%% These are done manually here -- doesn't perfectly flush left since
%%  need to allow space if you get up to double-digit enumeration. Is fine
%%  though.
\setlength{\leftmargini}{6mm}  %% not actually based on enumerate package
\setlength{\leftmarginii}{4mm} %%  (had already been done).
\setlength{\leftmarginiii}{4mm}
\setlength{\leftmarginiv}{4mm}

%% The following controls the look of the second-level in an enumeration list
\renewcommand{\labelenumii}{\theenumii}
%% This will make list items like 1.1, 1.2, etc
%%\renewcommand{\theenumii}{\theenumi.\arabic{enumii}.}
%% This will make list items like A., B., etc.
%%\renewcommand{\theenumii}{\Alph{enumii}.}
%% This will make list items like a., b., etc.
\renewcommand{\theenumii}{\alph{enumii}.}

%% The following controls the look of the second-level in an enumeration list
%% This will make list items circles instead of stars
\renewcommand{\labelitemii}{$\circ$}
%% Sets up the levels of lists with types to use for each,
%%  e.g. level 2 uses small alphabetic characters and
%%  level 3 uses roman numerals.
\usepackage{enumitem}
\setenumerate{
  align=left,        % Left align labels
  topsep=0pt,        % Vertical space before the list
  labelindent=0pt,   % Space betw. margin of list and label
  %% Even though the specs say 0.25 inches for labelsep, need 0.01 here.
  labelsep*=0.01in,  % Space betw. numbers and text (note * is req'd)
  leftmargin=!,      % No space betw. margin of list and following lines
  itemindent=0pt,    % Hanging indentation (after first line)
  itemsep=0pt        % Vertical space between list items
}
\setenumerate[1]{label=\arabic*.}
\setenumerate[2]{label=\alph*.}
\setenumerate[3]{label=\roman*.}
\setenumerate[4]{label=\arabic*.}
\setenumerate[5]{label=\alph*.}
%\setenumerate{nosep} % This needs to be here for itemsep above to be recognized
\setitemize{
  align=left,        % Left align labels
  topsep=0pt,        % Vertical space before the list
  labelindent=0pt,   % Space betw. margin of list and label
  %% Even though the specs say 0.25 inches for labelsep, need 0.01 here.
  labelsep*=0.01in,  % Space betw. numbers and text (note * is req'd)
  leftmargin=!,      % No space betw. margin of list and following lines
  itemindent=0pt,    % Hanging indentation (after first line)
  itemsep=0pt        % Vertical space between list items
}
%\setitemize{nosep}   % This needs to be here for itemsep above to be recognized

%% Hanging indent of the bibliography items.
\setlength{\bibhang}{0.25in}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% For display of pseudocode
\usepackage{algorithm}
\usepackage{algpseudocode}
\usepackage{linegoal}
%% A \Let command for defining assignments within the algorithmic environment
%%  which supports automatic indentation when the second argument is too long to
%%  fit on one line
\newcommand*{\Let}[2]{\State #1 $\gets$
\parbox[t]{\linegoal}{#2\strut}}
%% A \State command that supports automatic indentation when the argument's
%% content is too long to fit on one line
\newcommand*{\LongState}[1]{\State
\parbox[t]{\linegoal}{#1\strut}}
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Other included packages
\usepackage{cite}
%% Need array when specifying a ragged right column:
%%  >{\raggedright\arraybackslash}{p2in}.
\usepackage{longtable,array}
%% For figures in chapter subdirectories
\usepackage{import}
%% For inclusion of figures
\usepackage{graphicx}
\usepackage{verbatim,fancyvrb}
%% Provides \ifthenelse and \isempty
\usepackage{xifthen}
\usepackage{color, colortbl}
%% For dashed lines in tables
\usepackage{arydshln}
%% So paragraphs will have a blank line between them
\usepackage[parfill]{parskip}
\setlength{\parskip}{4pt}
%% So links will anchor at figure, not caption
\usepackage{hypcap}
%% For two-panel plots
\usepackage{subfig}
%% For mathlarger, which makes equations bigger
\usepackage{relsize}
%% For booktabs, which allows xtables to render moew nicely
\usepackage{booktabs}
%% For cells spanning multiple rows in xtables
\usepackage{multirow}
% To do 'for' loops in latex
\usepackage{pgffor}
% For float barriers
\usepackage{placeins}
% Include PDFs (i.e., whole page)
\usepackage{pdfpages}

\usepackage{textcomp}
\usepackage{lastpage}

% https://tex.stackexchange.com/questions/311132/how-to-style-hrefs-underlined-and-coloured-throughout-the-document
\usepackage{xcolor,soul}
\usepackage{pdfcomment}

% Underlines
\usepackage[normalem]{ulem}
% hack into hyperref (from https://tex.stackexchange.com/q/208808)
\makeatletter
\newcommand*{\link}{\begingroup\@makeother\#\@mylink}
\newcommand*{\@mylink}[2]{\href{#1}{\uline{#2}}\endgroup}
\makeatother

% Included so that the kableExtra::linebreak function can be used
\usepackage{makecell}

%% Allows the french abstract to be pasted in with special characters intact
%% Make sure maindoc.rnw is saved in utf8 encoding.
%% In emacs you can change the coding with Ctrl-x Ctrl-m f
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

%% The \sum command creates encoding errors in the final PDF so it is replaced
%%  globally here with Sigma. The * in DeclareMathOperator* makes the limits
%%  appear above and below the Sigma symbol instead of in front of it.
%% This declaration means you can just use \sum in the latex code and the errors
%%  for character encoding will not occur.
\usepackage{scalerel}
\let\oldsum\sum
\DeclareMathOperator*{\summ}{\scalerel*{\Sigma}{\oldsum}}
\renewcommand{\sum}{\summ}

%% To create alternate text for figures using
%%   \pdftooltip{ \includegraphics{fig-file} }
%%              {Figure~\ref{fig:haida}}   (see longer examples in readme)
\usepackage{pdfcomment}

%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% Variables used in assessments
%% For subscripts in text mode
\newcommand{\subscr}[1]{$_{\text{#1}}$}
%% Allow newline breaks in a table cell = Multi-Line-Cell = mlc
%%  syntax is \mlc{first line\\second line\\more if necessary..}
%% Don't change the name of this, as it is embedded in R xtable code.
\newcommand{\mlc}[2][c]{\begin{tabular}[#1]{@{}c@{}}#2\end{tabular}}

\newcommand{\Bmsy}{B_\mathrm{MSY}}
\newcommand{\umsy}{u_\mathrm{MSY}}

% Multi-letter identifier (i.e., multi-character variable such as `SB`)
\newcommand{\mli}[1]{\mathit{#1}}
% Better treatment of input (no extra trailing space)
\newcommand{\inputsp}[1]{\input{#1}\unskip}

% Custom commands:
\newcommand{\sQuote}[1]{`#1'}
\newcommand{\dQuote}[1]{``#1''}
\newcommand{\eqn}[1]{\begin{equation}#1\end{equation}}
\newcommand{\gfrac}[2]{\genfrac{}{}{}{0}{#1}{#2}}

% eor - Show two things with a vertical bar between them. e.g. A|B
\newcommand{\eor}[2]{{#1$\Vert$#2}}

% bM - makes equations larger
\newcommand{\bM}[1]{\mathlarger{\mathlarger{#1}}}
%% ------------------------------------------------------------------------------

\fancypagestyle{nofooter}{%
\fancyfoot{}%
}

%% ------------------------------------------------------------------------------
%% Frontmatter: set up first few pages including the title page, TOC, and abstract
%% Note that this requires some custom variables that you need to set in the main
%% document (e.g., title, authors, year, report number)
\linenumbers
\modulolinenumbers[1]
\def\frontmatter{%

\thispagestyle{empty}

\newgeometry{top=0.55in,bottom=0.55in,left=1in,right=1in}

\includegraphics[width=9.14cm]{\locRepo/images/Fip-stacked-DFO-EOS-eng_bw.png}

\vspace{1.5mm}

\textbf{Canadian Science Advisory Secretariat (CSAS)}

\vspace{0.4mm}

\hrule

\vspace{1.8mm}

\textbf{Research Document \rdYear{}/\rdNumber{}}\\

\vspace{2mm}

\textbf{\rdRegion{}}

\vspace*{\fill}
\begin{center}

\textbf{\rdTitle{}}
\vspace{.35cm}

\rdAuth{}

\vspace{.35cm}

\rdAuthAddy{}

\end{center}
\vspace*{\fill}

\hrule

\vspace{-0.9mm}

% \vspace{-4.0mm}
\parbox{9cm}{\rdMonth{} \rdYear{}}%
\begin{minipage}[t]{7.48cm}
\flushright
\includegraphics[width=3.54cm]{\locRepo/images/canada_bw.png}%
\end{minipage}

\clearpage

\restoregeometry

\vspace*{\fill}

\begin{center}
\textbf{Foreword}
\end{center}
\vspace{0.2mm}

This series documents the scientific basis for the evaluation of aquatic resources and ecosystems in Canada.  As such, it addresses the issues of the day in the time frames required and the documents it contains are not intended as definitive statements on the subjects addressed but rather as progress reports on ongoing investigations.

\vspace{4.2mm}

\begin{center}
\textbf{Published by:\\}
\vspace{1.9mm}
Fisheries and Oceans Canada\\
Canadian Science Advisory Secretariat\\
200 Kent Street\\
Ottawa ON K1A 0E6\\
\vspace{0.17cm}

\link{http://www.dfo-mpo.gc.ca/csas-sccs/}{http://www.dfo-mpo.gc.ca/csas-sccs/}\\
\link{mailto://csas-sccs@dfo-mpo.gc.ca}{csas-sccs@dfo-mpo.gc.ca}

\vspace{0mm}
\includegraphics[scale=0.96]{\locRepo/images/recycle.png}

\vspace{-1mm}
\textcopyright\ Her Majesty the Queen in Right of Canada, \rdYear{}\\
ISSN 1919-5044
\end{center}

\vspace{-0.2mm}

\textbf{Correct citation for this publication:}\\
\vspace{2mm}
\hangindent=0.6cm \rdAuthRev{}
\rdYear{}.
\rdTitle{}.
DFO Can.\ Sci.\ Advis.\ Sec.\ Res.\ Doc. \rdYear{}/\rdNumber{}.
\pageref{TRlastRoman}{} + \pageref{LastPage}~p.

\vspace{0.2mm}
\textbf{Aussi disponible en fran\c cais :}\\
\vspace{2mm}
\hangindent=0.6cm \emph{\citationOtherLanguage{}}\\

\vspace*{\fill}

\thispagestyle{nofooter}

\clearpage

\fancypagestyle{plain}{%
\fancyhf{} % clear all header and footer fields
\fancyfoot[C]{\sffamily\selectfont\thepage} % except the center
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}}
\pagestyle{plain}

\TableOfContents

% \fancypagestyle{plain}{%
% \fancyhf{} % clear all header and footer fields
% \fancyfoot[C]{\sffamily\selectfont\thepage} % except the center
% % \fancyfoot[L]{\slshape \rightmark}
% % \fancyfoot[L]{\slshape \leftmark}
% \renewcommand{\headrulewidth}{0.4pt}
% \renewcommand{\footrulewidth}{0.4pt}}
% \pagestyle{plain}

\Main

\rdAbstract{}

\label{TRlastRoman}

\clearpage

% The next two lines are required to start off numbering
\pagenumbering{arabic}
\setcounter{page}{1}

}% End of frontmatter
%% ------------------------------------------------------------------------------

\newenvironment{CSLReferences}[3] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}

**Comment by obradovichs** [comment]
@maburton See also issue #31?

**Comment by seananderson** [comment]
That's great @maburton. Thanks for looking into this. I can't say I follow everything happening here, but if there's a change you can make to the .sty files (French and English) to fix this (without creating other problems) then feel free to make a pull request and we'll merge it in.

**Comment by cgrandin** [comment]
We did solve this for single page landscape tables quite some time ago, but it won't work for longtables that span multiple pages. That's the real issue, and I've spent far too much time on it. I have a working code for it, without headers and footers but I cannot get the headers and footers to rotate on multiple pages with any sort of reliability. We need a solution that works for any combination of tables both single-page and multi-page. We aren't there yet, but I haven't lost hope (surprisingly).

**Comment by cgrandin** [comment]
This has all been resolved as of 9127d355a8316f052530f51cf3d8efed8dcf89cd
YAY!
Thanks to @maburton for figuring it out.

**Comment by ricardd** [comment]
@cgrandin I am following the Wiki (https://github.com/pbs-assess/csasdown/wiki/How-to-make-landscape-tables) to have landscape tables, but the page number appears twice: 

![Untitled](https://user-images.githubusercontent.com/1110182/110973326-80a80d80-8333-11eb-834f-06da7a39d44f.png)

any suggestions?

**Comment by maburton** [comment]
@ricardd I imagine you are missing some sort of pagestyle{empty} or making the portrait header and footer empty. Which type of document are you creating?

**Comment by ricardd** [comment]
@maburton a ResDoc

**Comment by maburton** [comment]
@ricardd @cgrandin The wiki tells users to call the environment "landscape" while the sty file specifies the environment "landscapepage". I think @ricardd if you call "landscapepage" instead you should no longer have that issue, and @cgrandin you might need to update the wiki. 

The wiki suggests:
\begin{landscape}
```{r chunkname}
 csas_table(data)
```
\end{landscape}

It's my understanding it should be:
\begin{landscapepage}
```{r chunkname}
 csas_table(data)
```
\end{landscapepage}

in order to match the latex environment specified in the .sty files

**Comment by ricardd** [comment]
@maburton , yes this works, now I recall our chats from a few weeks back, thanks

and wiki updated accordingly

**Comment by cgrandin** [comment]
Thanks @maburton for spotting that. Thanks @ricardd for fixing it. I swear I re-read that wiki about 10 times before posting it..

**Comment by grinnellm** [comment]
I switched from using the `\turn` environment to this one, `\landscapepage` which seems quite nice, thanks. Sorry if I am missing something, but the header text is missing above the header rule: "Pacific Region Science Response...". However I do have page numbers below the footer rule.

**Comment by maburton** [comment]
Hi @grinnellm. Good catch! I wrote the ` \landscapepage` environment using resdoc as a template (which doesn't have that text). I will work on a solution.

**Comment by maburton** [comment]
I found a solution. See pull request #194
