### ISSUE TITLE
Cross-reference numbering points to higher level header

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#179]
**Describe the bug**

For this structure of the Appendix:

```
# Abundance Estimation {#app:AbdEst}


## Spawner Data Review  {#app:SpnReview}

Text, Text,text
```

the in-text cross-reference ```spawner estimates for indicator systems (Appendix \@ref(app:SpnReview))``` shows up as *review of spawner estimates for indicator systems (Appendix C)*,  rather than *C.1*

**To Reproduce**

This seems to happen wherever I cross-reference the first sub-section of a chapter.

**Expected behavior**

reference should point to the subsection (e.g. C.1)

**Observed behavior**

reference points to the chapter header (e.g. C)

**Desktop (please complete the following information):**
 - Operating system: Windows
 - R version: "R version 4.0.3 (2020-10-10)"
 - csasdown version:  ‘0.0.8.9001’

**Comment by cgrandin** [comment]
This only works for one layer, e.g. Appendix sub section A.1, A.2, B.3 etc. You will get the same issue agian if you try to do a sub-subsection that begins with three hash symbols. So you cannot have A.1.3 or B.2.1 referenced. They will just be referenced as A.1 and B.2.

The solution involved adding manual counters because the Appendices are starred chapters (unnumbered). 

techreports are entirely different and this code does not affect them.

**Comment by cgrandin** [comment]
See ee60ea33671b239b8f9c1d3af5551e9a96d4813a, 5c6e86e19423e337c0b1cfd8452de8752364135a, c9f5a8b9392b652cbd89c2cd25cba2b26a56f892, 3f38f7336b51e27e54e1d7ccfedc7d3f6cc3ac2e, 1ec8c057165de373d5210aa42c779b08a004f630, 5cfd3eab1bb00bf7ade57e4e2b30c2593c35f9ce
