### ISSUE TITLE
Use `officer::body_add_toc()` function to add table of contents to `resdoc_word` output

### ISSUE THREAD

**Issue by PaulRegular** [pbs-assess/csasdowntex#186]
I worked up some code to add a title page and a table of contents to a Res Doc I was drafting using `resdoc_word`. Putting this idea out here in case there is interest in augmenting the `add_resdoc_docx_titlepage` function.

**Comment by seananderson** [comment]
I don't think the Word version is getting used much around here because of minor lingering issues. If it's not too much trouble, I think that would be great to include, along with any other improvements you can think of to the .docx workflow after your experience with NAFOdown. If we could produce a good .docx product that would solve some of the translation pain.

**Comment by cgrandin** [comment]
This was addressed in the referenced issue on May 5, 2021 and has a corresponding commit so it looks to be done.
