### ISSUE TITLE
Added Docker container support

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#189]
I've added support for Docker containers. This is considered Beta so **any** feedback would be great.
See the two wiki Howtos for instructions:

https://github.com/pbs-assess/csasdown/wiki/Compiling-your-document-in-a-Docker-container

and

https://github.com/pbs-assess/csasdown/wiki/Building-a-new-Docker-image-manually

The Docker image is currently located at https://hub.docker.com/repository/docker/cgrandin/csasdown but we could make an organization account if there is enough interest.

The image is built up from **rocker/tidyverse** (https://hub.docker.com/r/rocker/tidyverse) so it has all tidyverse packages loaded as well.

I would like to create images tied to Git tagged versions in the future

**Comment by SOLV-Code** [comment]
Thank you for setting this up. 

I have worked through all the steps of  the first wiki (https://github.com/pbs-assess/csasdown/wiki/Compiling-your-document-in-a-Docker-container), and the techreport template knitted perfectly (and much faster than the first knit of a new install used to be...).  I did have some rough spots on the way there, but mostly due to not following your steps exactly, or not being familiar with the container concept. For example, I spent some time trying  to navigate to my report folder from inside the RStudio browser instance, until I clued in that it is already the working directory, just self-contained (hence the name, I guess) and you can't access higher-level folders.  As this moves out of beta, consider adding a bit more background like this to the wiki...

Next step: setting up the Latex and R packages as per your other wiki.

Some more general question about workflow:
* Should I do dev work (e.g. tinkering with plots) in regular RStudio, and then switch to the container for knitting? Or are you moving towards doing everything in the browser instance?
*  How do I switch between projects? Within the Rstudio instance, I can click on "Open Project", but can't move up the path to a different folder. Should I create a folder "R Projects",  then navigate there in the powershell, then do ```docker run -d -p 8787:8787 --mount type=bind,source="$(pwd)",target=/home/rstudio cgrandin/csasdown```? If I then put all my R projects there, can I switch between projects from within the instance, without powershell mounting? (I am frequently in a situation where the "main" work of the day gets interrupted for a quick fix on a different doc, and when I'm in regular RStudio I can just open another project.)

**Comment by SOLV-Code** [comment]
### Building a new Docker Image

* Could add a quick clarification in the wiki that you need to fork and clone the csasdown repo first, then change the files in the ```docker``` folder.

* the ```docker build``` step failed due to some tinytex / tlmgr issue.  That may be the same problem that sent me to try the docker approach in the first place. (but it kind of makes sense: you need to have a working setup of all the packages before you can build a working image). Am i back to square 1 until I get things working locally?  Once I've got things working, I will build a docker image.


```
#6 117.0 [64/66, 00:26/00:26] install: wrapfig [10k]
#6 117.4 [65/66, 00:26/00:26] install: xifthen [3k]
#6 117.8 [66/66, 00:27/00:27] install: zref [15k]
#6 118.2 tlmgr: action install returned an error; continuing.
#6 118.2 running mktexlsr ...
#6 118.3 done running mktexlsr.
#6 118.4 tlmgr: An error has occurred. See above messages. Exiting.
#6 118.4 tlmgr: package log updated: /opt/TinyTeX/texmf-var/web2c/tlmgr.log
#6 118.4 tlmgr: command log updated: /opt/TinyTeX/texmf-var/web2c/tlmgr-commands.log
------
executor failed running [/bin/sh -c wget -qO-     "https://github.com/yihui/tinytex/raw/master/tools/install-unx.sh" |     sh -s - --admin --no-path   && mv ~/.TinyTeX /opt/TinyTeX   && /opt/TinyTeX/bin/*/tlmgr path add   && tlmgr install tabu varwidth nowidow bookmark ncctools lineno     fancyhdr caption tocloft ragged2e everysel microtype     everypage pdflscape textpos enumitem algorithms algorithmicx     linegoal etex-pkg zref cite import xifthen ifmtarg colortbl     arydshln parskip oberdiek subfig relsize multirow     fp ms pgf placeins eso-pic pdfpages lastpage     soul pdfcomment datetime2 tracklang marginnote soulpos     ulem makecell scalerel was setspace sectsty tocbibind     hanging babel-english babel-french titlecaps ifnextok     textcase doi appendix soulpos chngcntr amsfonts soulutf8      booktabs longtable array multirow wrapfig float colortbl       threeparttable threeparttablex xcolor     dvips   && tlmgr path add   && Rscript -e "tinytex::r_texmf()"   && tlmgr init-usertree   && chown -R root:staff /opt/TinyTeX   && chmod -R g+w /opt/TinyTeX   && chmod -R g+wx /opt/TinyTeX/bin]: exit code: 1
PS C:\Users\jeffv\OneDrive\GIT\csasdown\docker>
```

The packages I'm trying to add are:

Latex
```
	booktabs longtable array multirow wrapfig float colortbl \
	threeparttable threeparttablex xcolor 
```
These come from https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf
I use these for color-coded tables. Could you add these to your build?



R packages:
```
install.packages("janitor")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("caret")
install.packages("e1071") 
```
but these have nothing to do with knitting / markdown. I can retool the report so that it runs all the analyses in regular RStudio with these packages and produces outputs (csv, png) , then switch over to the docker image to knit.

**Comment by cgrandin** [comment]
It sounds like you are totally understanding this which is great. Thanks for the feedback!

You need Linux to build a docker image using the Dockerfile.
The good news though, is that Microsoft recently developed this thing called the WSL2 subsystem which is a full native Linux implementation inside the Windows Kernel. So, you need to install this. I recommend installing Ubuntu as your Linux distro (from the Microsoft Store). It's all laid out in the instructions in the link here.

https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10

Once you have the Linux subsystem installed you can run Linux scripts (including docker build scripts like this) on Windows without issue. I believe you can run them from Powershell, but I prefer to go into the Linux shell itself and run them.

Here's what the Ubuntu program icon looks like.  Click to open it up:
![image](https://user-images.githubusercontent.com/4551051/120455610-c4664e00-c349-11eb-9b9d-b2d050d4ffad.png)

Once you install Ubuntu and open it up, your `C:\` drive is mounted in it like this:
`/mnt/c/`
So to change to `C:\Users\grandin` I would type:
`cd /mnt/c/Users/grandin`

and then look at the directory contents:
`ls`

Once you have navigated to the docker directory and made your changes to the Dockerfile, build the image:
`docker build . -t newid/csasdown`

Note that you're not really meant to change the `Dockerfile` and `install_packages.R` files in csasdown, but to make a copy of them and put them somewhere else where you make your changes. You will make a new, personal image which you then run. It won't be part of the csasdown image.

I will add the packages you suggest to the csasdown image though as they are obviously needed!


Warning, once you start using Linux you won't want to use Windows anymore!

**Comment by cgrandin** [comment]
To answer your other question about folder availability in the container, typically most folks I think have an `.Rproj` file for each project and it is totally dedicated to that project. So there may be several RStudio instances running at any given time.

This is based on that idea with the VOLUME being set to the local working directory (where you executed the `docker run` command). So you can only access that directory and any subdirectories of it. If you really want to have full access to your whole `C:\` drive, just execute the `docker run` command from your `C:\` directory and it will mount the whole thing as a VOLUME. Then you can freely move about your system inside the Rstudio instance.

Also, the idea here is that you do everything inside this container. There is no need to do anything locally because the entire build environment is encapsulated (once we make sure everything has been included). The idea is that it will be impossible to have surprise system configuration issues that screw you over at the 11th hour (it's happened to me so many times), and that everyone involved in a project are running things from a common base setup.

Again thanks for testing this!

**Comment by SOLV-Code** [comment]
Much to learn! Thank you for all your help.  

WSL2 was installed as part of the Docker Desktop setup, but I haven't done the extra step of the Ubuntu install. Will try this later.

 I think I still have to navigate through some conceptual blocks:
- container vs image (I see now that containers like "cool_nash" get generated every time I do the ```docker run``` call for a new project.  Once I figure out how to give them meaningful names, I think I'll be good to go re: switching between projects. Just need to think of the container as equivalent to the ```.Rproj```, which is specific to each project)
- Starting a specific container: currently it seems that ```localhost:8787``` in the browser will always start whatever container was last started with ``` docker run```. Is there a way of switching to another container straight from the ```Docker Desktop```? Or do have to just start things from the powershell (or linux) every time?
- Limitations/Intent of RStudio browser instance / container: I think I can still add R packages inside the container from an R script, but your point above is that this is bad practice?  So do analysis dev in regular RStudio (don't know ahead of time which packages needed), then set up a custom image, then switch over to the container for knitting?

Re: building image

Where would I put the modified ```Dockerfile``` and ```install_packages.R```

**Comment by cgrandin** [comment]
A container is an instance of an image. So when you run and image (which is what that `docker run` command does) it creates a new container. To name it, add `--name myname` to the run command. You should clean up (delete) all the containers and images once in awhile so there's no clutter. You can delete all of them and re-pull `cgrandin/csasdown` anytime. There's also a button under the "bug" button for `Clean/Purge data` which removes all traces of layers of images.

You can also run an image, thus creating a new container in Docker Desktop by clicking `Images` on the left and hovering over the image, then click the run button next to the image.

Sure you can run your analysis in local Rstudio if you want. This docker image just contains everything you need to create the document once you're ready.

You can re-run a container already created previously by hovering over it and then pressing the Play button (arrow) inside Docker Desktop

**Comment by SOLV-Code** [comment]
### Update
I can generate a named container  directly in the ```docker run``` call with something like ```docker run -d -p 8787:8787 --name SkeenaNassSKDataRep --mount type=bind,source="$(pwd)",target=/home/rstudio cgrandin/csasdown```
However, when I tried to change the port, it didn't work. I tried ```8989:8989``` which generated the container with this port, but ```localhost:8989``` in the browser didn't work. Turns out I need to learn about ports. Or should all the containers have the same 8787 port? If so, how do I switch to a different one in the browser? Is by stopping one and running another in Docker desktop, and always using ```localhost8787```?

**Comment by cgrandin** [comment]
You can use another port like this:

`docker run -d -p 8000:8787 --mount type=bind,source="$(pwd)",target=/home/rstudio cgrandin/csasdown`
`localhost:8000`

The 8787 must be used because that is what RStudio server uses to communicate. You change the first number only
You need to be careful with ports because there are lots or reserved ones. I think if you stick to the 8000's you'll be ok

You can have as many tabs running with different instances of Rstudio as you want, with different ports

**Comment by SOLV-Code** [comment]
Thank you, that works.

**Comment by cgrandin** [comment]
@SOLV-Code I updated the cgrandin/csasdown docker image to contain the packages you listed above (both R and Latex).

The `array` package does not exist in the `tlmgr` package system though (Tinytex/Texlive). I think that was the problem you were having before I suggested the WSL2 install. Thanks for the clarification that Docker installs WSL2. That makes things simpler.

If the `array` package is necessary it will have to be loaded in manually through a zip file.

**Comment by SOLV-Code** [comment]
Thank you again. I will try the new docker image later today, and let you know. Also will start getting the word out to co-authors who haven't been able to get knitting to work. I think this is a huge leap forward in terms of  expanding the user base.

**Comment by SOLV-Code** [comment]
### Update (not an urgent issue)

The new image works for several of my reports, but for one of them it crashes on a csas_table chunk. However, the report (currently) works again when knitting from regular RStudio, so I'm parking the chase for the issue for a bit. Just in case there's something obvious you could spot, I'm including the details below, but this is not holding up any work, so there's no need to spend any of your time on it.

### Details

When I run it with ``` bookdown::render_book("index.Rmd")```, the error message on the console is:
```
Quitting from lines 2489-2507 (SkeenaNass_Sockeye_DataReview_DRAFT.Rmd) 
Error in temp_sub(target_row, new_row, out, perl = T) : 
  input string 1 is invalid UTF-8
```

If I run it with the **Knit** button in the container, it provides additional detail in the markdown tab:
```
calls: ... eval -> _fseq -> freduce -> csas_table
```

Does any of this ring a bell? could it be connected to the ```array``` Latex package  you flagged above? 

There's no really fancy formatting in this one. The table chunk is

```{r MajorProgramsNass, echo = FALSE, results = "asis"}

n.majproj.nass <- sum(survey.summary.major$Basin == "Nass")

survey.summary.major %>% dplyr::filter(Basin == "Nass") %>%
  select(-FAZ, -WS, -Order,  -Basin) %>%
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
   mutate_all(function(x){gsub("%", "\\\\%", x)}) %>%
   csas_table(format = "latex", escape = FALSE, font_size = 10,
                  caption = "(ref:MajorProgramsNass)") %>%
   #kableExtra::column_spec(1, width = "3em") %>%
   kableExtra::column_spec(1, width = "4em") %>%
   kableExtra::column_spec(2, width = "6em") %>%
   kableExtra::column_spec(3, width = "6em") %>%
   kableExtra::column_spec(4, width = "4em") %>%
   kableExtra::column_spec(5, width = "18em") %>% 
   kableExtra::column_spec(6, width = "4em") %>%
   kableExtra::row_spec(1:(n.majproj.nass-1), hline_after = TRUE) 

```

What about the container would be different from my local install that the content of the table (i.e. a special symbol) causes one to crash and not the other?

### Side Note

One of the issues I was running into earlier this week was also related to ```csas_table```.
I had the argument ```landscape = FALSE``` in there, which caused the knit to crash due to ```unused argument``` after I installed the latest version of csasdown. Once I figured out that was happening, it was a quick fix, and didn't affect the final pdf at all.

**Comment by cgrandin** [comment]
Can you send me a whole working code chunk (minimal working example) I can put into a new tech report template to reproduce the issue? Then I’ll be able to track it down. By working chunk I mean one that throws the error...

It looks like a UTF 8 font issue

**Comment by SOLV-Code** [comment]
Thank you, will do. but probably won't get to it until the weekend. Lots of catching up to do...

**Comment by cgrandin** [comment]
I did try this and it works, but I  made up data for the table. I need the `survey.summary.major` object

**Comment by SOLV-Code** [comment]
Thank you! Sending you csv via e-mail.  Table comes out like this when I knit in regular Rstudio, but crashes on the UTF-8 issue inside the container. 
![NassTable](https://user-images.githubusercontent.com/30556192/120858279-6bf4a380-c537-11eb-9867-c042bd8949f2.PNG)

**Comment by cgrandin** [comment]
This is because the csv file was saved in a non-UTF-8 editor. I think it renders correctly in Windows because the TexLive distribution has the correct fonts installed and/or converts it successfully on your machine. The container is in Linux so it fails. Even in Windows this problem will come to bite you later so you need to make sure to save all CSV files in a UTF-8 editor, not Excel.

To fix it I opened Visual Code editor which is the easiest to understand and change encodings in (https://code.visualstudio.com/download).

This thread tells you how to change encodings: https://stackoverflow.com/questions/30082741/change-the-encoding-of-a-file-in-visual-studio-code#:~:text=In%20the%20bottom%20bar%20of,Click%20Save%20with%20encoding%20.

And when you do you can see the erroneous characters as a white diagonal background with a question mark in it.:

![image](https://user-images.githubusercontent.com/4551051/120883792-0c78b100-c594-11eb-86fb-412c20720dcb.png)

I fixed them but you should check as I guessed they were supposed to be Nisga'a and Wit'set canyon. Anyway check your email for the file.

**Comment by SOLV-Code** [comment]
That is some very impressive sleuthing! Thank you for tracking this down. I've had previous trouble with ```%``` or ```^```, but ``` Nisga'a``` etc always rendered fine in tables.  I am going through now and re-saving all the csv inputs as UTF-8. Over time, I'll also have to change  all my  ```write.csv()``` calls to include ``` write.csv(DF, FILENAME, row.names = FALSE, fileEncoding = "UTF-8")```, as per   https://stackoverflow.com/questions/3792846/how-to-export-a-csv-in-utf-8-format. Doing this now, and will try the container again a bit later this morning.

**Comment by SOLV-Code** [comment]
Turns out I also need to change all the ```read.csv()``` to include ```encoding="UTF-8"```. I think this will address a lot of unexpected stuff that would pop up from time to time. As you wrote earlier at some point: just switch to Linux :-)
I think I'm drifting in that direction...

**Update**

actually it has to be ```fileEncoding="UTF-8-BOM"``` in ```read.csv()``, as per final point in https://www.johndcook.com/blog/2019/09/07/excel-r-bom/

**Comment by SOLV-Code** [comment]
**Container Success!**. After implementing all the ```UTF-8-BOM``` fixes, the container based on your docker image now knits the document from the command line with ```bookdown::render_book("index.Rmd")```.

Note that it crashes during the knit if I try to use the *knit* button in the browser-based RStudio instance, with the following messages on the R markdown tab:
```
lmgr: package repository https://ctan.math.ca/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/2, ??:??/??:??] install: environ [2k]
[2/2, 00:01/00:01] install: trimspaces [1k]
chmod(420,/opt/TinyTeX/tlpkg/texlive.tlpdb) failed: Operation not permitted at /opt/TinyTeX/tlpkg/TeXLive/TLUtils.pm line 1280.
running mktexlsr ...
chmod(420,/opt/TinyTeX/tlpkg/texlive.tlpdb) failed: Operation not permitted at /opt/TinyTeX/tlpkg/TeXLive/TLUtils.pm line 1280.
done running mktexlsr.
tlmgr: package log updated: /opt/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /opt/TinyTeX/texmf-var/web2c/tlmgr-commands.log
TLUtils::add_remove_symlinks: add of symlinks had 1 error(s), see messages above.
add_link_dir_dir: destination /usr/local/bin not writable, no links from /opt/TinyTeX/bin/x86_64-linux.
tlmgr: An error has occurred. See above messages. Exiting.
```
This is not an issue for users that follow your wiki instructions exactly, but might be worth mentioning somewhere...

**Comment by cgrandin** [comment]
Great! You may want to think about using readr::write_csv() and read_csv() for a multitude of reasons which you can Google but I highly recommend switching. 
Interesting about the knit button, I never use it because I’m always debugging and never get to be the end user haha. I will look into it though. 

Many thanks for all the feedback!

**Comment by SOLV-Code** [comment]
re: readr::read_csv(), it's just a matter of old habits. I've been typing read.csv() since my days battling with S-Plus 4 on Linux machines in the last millenium.  But I will eventually remember to switch...

**Comment by SOLV-Code** [comment]
just a quick note, because this popped up as I was cleaning out old notifications:

I *have* switched to ```read_csv()```, but now ran into an issue with a large data file. It was reading a column with lots of NA as a logical rather than numeric.  This seems to be [by design](https://github.com/tidyverse/readr/issues/839), and the tidyverse fixes are all a bit convoluted. ```read.csv()``` works as is. Just sayin'...

**Comment by cgrandin** [comment]
Yes, and I admit it messed me up at first as well. Here's why: https://github.com/tidyverse/readr/issues/662#issuecomment-340228670

You can use the `guess_max` argument to make it go past the first 1000 rows for guessing the type.

**Comment by SOLV-Code** [comment]
Thank you for the *guess_max* tip. Once ```read.csv``` worked I didn't look any further :-)

**Comment by SOLV-Code** [comment]
Thank you!
