### ISSUE TITLE
Feature question: watermarks in pdf?

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#195]
As part of the pre-CSAS review process for a res doc, the team is wondering whether we can include a *DRAFT* watermark in the csasdown pdf output.  

I don't remember seeing this in any of the templates when you start a new *csasdown* document, and a quick search through the issues didn't produce any results.  I found two stackoverflow threads with potential solutions ([here](https://stackoverflow.com/questions/32748248/watermark-in-rmarkdown) and [here](https://stackoverflow.com/questions/39746947/how-to-add-a-watermark-image-on-rmarkdown)), but before going down the road of exploring this, I wanted to check whether this is maybe already built into *csasdown*.  And if not, have you tried this before, and it got too convoluted, and it's probably not worth pursuing?

Also to consider: some of the co-authors are relying on the [Docker container created by @cgrandin ](https://github.com/pbs-assess/csasdown/issues/189), and so trying to rely on latex packages that are not already in there would create other challenges...

**Comment by cgrandin** [comment]
I have thought about this several times but then had other things to deal with so I haven't added the watermark.

I'm happy to hear that the Docker image is being used. It's easy enough to update that so if there are any more latex packages that need to be added to the container just tag me on the commits/issues and I'll update it. I should do so anyway as it's been 5 months since it was created. If people are using it I can update it more regularly.

**Comment by SOLV-Code** [comment]
The solution from [here](https://stackoverflow.com/questions/32748248/watermark-in-rmarkdown) worked right away.

Just modified index.Rmd like this:
```
header-includes:
# - \usepackage{tikz}
- \linenumbers
# rest is from page 4 of https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
- \usepackage{booktabs} 
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{draftwatermark}    # <------------ ADDED THIS
```
and then added this at the beginning of introduction.Rmd
```
\SetWatermarkText{DRAFT}
```

So those of us who are knitting in a local install can generate the watermark, but it would be great if this could be added to the Docker image at some point. Thanks!

**Comment by cgrandin** [comment]
Apparently right now CSAS does not currently require a watermark DRAFT on the pages, and may reject it if submitted. Do you have any clarification on this? Will they allow it?

I will add it to the project as a new YAML toggle instead of under the `prepub` toggle as I had originally thought

**Comment by seananderson** [comment]
I think this is for well before submission to CSAS. I'm not sure we need a new YAML toggle if all it takes is 

`- \usepackage{draftwatermark}` and `\SetWatermarkText{DRAFT}`

And having the user do that makes it transparent how to change the text without complicating the default template.

But if it doesn't go in the YAML, we should get that into the wiki.

**Comment by cgrandin** [comment]
I added a YAML toggle for this. It turns out you don't even need the `\SetWatermarkText{DRAFT}`, just including  the latex watermark package automatically adds the watermark.

All three document types have the toggle and there is some new error checking to make sure you have not set any of `line_nums`, `lot_lof`, or `draft_watermark` to TRUE if `copy_sty` is FALSE.

I updated the Docker image (https://hub.docker.com/repository/docker/cgrandin/csasdown) with the newest R and tidyverse available for Docker (`rocker/tidyverse:latest` - https://hub.docker.com/r/rocker/tidyverse) and the csasdown inside it is at commit that includes all the changes up to today: acba155d11a7894a31c1390d372ba2bc0892a7d3.

Old projects will need to have `draft_watermark: true` added to the YAML, but new ones have it included.

![image](https://user-images.githubusercontent.com/4551051/140039068-0fdeb323-c7c8-471d-8878-ec8f69597324.png)

Commit which solves the issue: acba155d11a7894a31c1390d372ba2bc0892a7d3

**Comment by SOLV-Code** [comment]
Thank you.

Just as an after-the-fact clarification. The draft res doc is going out to a large group of reviewers (ADFG and DFO tech folks, PSC tech committee) before submission to CSAS, and because the csasdown pdf already looks so polished, the team wanted to make sure this doesn't get misinterpreted as a final report by any of the recipients...
