### ISSUE TITLE
Cleanup tmp files on.exit or before rendering again

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#211]
Using the new `csasdown::render()`, if something goes wrong while compiling, one can end up with files like this:

![image](https://user-images.githubusercontent.com/19349/180049111-de03670a-2c76-447b-9ea6-bf0ff687f837.png)

which keep building `tmp-tmp` etc. with each having extra injected bilingual chunks.

```
Duplicate chunk label 'bilingual-code', which has been used for the chunk
...
```

**Comment by cgrandin** [comment]
All the `tmp` files are deleted at the very beginning of the build in the `create_tmp_yaml_rmd_files` function.

The only way I can reproduce this is by doing this:
  
  ```
csasdown::render(verbose = TRUE, keep_files = TRUE)
csasdown::render(yaml_fn = "tmp_bookdown.yml", verbose = TRUE, keep_files = TRUE)
```

If someone wants to call it with the  `tmp_bookdown.yml` filename, that's their decision (but it doesn't make any sense to do it) and it will create `tmp-tmp-` filenames. That was breaking with duplicate bilingual code injection into `index.Rmd` so I made it so that multiple injections can't happen and it will render, in case someone does something weird like that.

Before rendering though,  it will ask whether or not you want to render in this odd scenario. If you say yes it will succeed.

Do you have a MWE of how you got into that situation?

**Comment by seananderson** [comment]
I believe it happens when you stop the compiling before it's done. A scenario would be that you do something illegal in the TeX code such that the LaTeX compilation is hanging for a while and then hit the escape key to abort. Or you start rendering and then realize you forgot to add something and you hit escape. It's happened to me a bunch of times and then it breaks future compilation. Sorry for not providing a MWE, it was more a reminder to get back to it myself.

**Comment by cgrandin** [comment]
That’s really baffling, the render() command only looks at _bookdown.yml by default which is never modified. Seems impossible unless there’s some weird recursion happening.

When I render a doc, the latex part doesn’t ever stop for me so I never had the option of pressing Esc.

**Comment by seananderson** [comment]
I think it's specific to clicking the 'Knit' button and stopping the rendering before it's finished. It builds up like this:
![image](https://user-images.githubusercontent.com/19349/180853479-b9d4fc0c-cac3-499c-b9d8-b663ff6ba16b.png)

and the YAML builds up like this:
![image](https://user-images.githubusercontent.com/19349/180853534-024c9f54-f061-4183-ad0a-1f31dda2025e.png)

I just added a check to delete old `tmp-` files and `gsub()` them out of the YAML if needed.

Now `tmp-` files get left behind if you abort and the YAML is left modified with `tmp-`, but they're cleaned up next time.

Also, these get left behind:
![image](https://user-images.githubusercontent.com/19349/180855591-2235fcb8-10de-4242-a7f8-f97e7516174a.png)

and I'm not sure if it's csasdown or bookdown that's created those. They don't harm anything though. Looks like they used `tempfile()`.

**Comment by cgrandin** [comment]
Those bookdown files are created by bookdown, not sure why. I've never had any hang around but I see them during rendering.
I bet they are deleted the next time you render something
