### ISSUE TITLE
Finish merging fsar branch into main

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#265]
Start by importing several packages for fsar_plot_base.

```
importFrom("grDevices", "grey")
     importFrom("graphics", "axis", "box", "layout", "legend", "lines",
                "mtext", "par")
     importFrom("stats", "arima.sim", "rnorm")
```

Also 

```
Found the following file with non-ASCII characters:
     R/plot-timeseries.R
   Portable packages must use only ASCII characters in their R code and
   NAMESPACE directives, except perhaps in comments.
   Use \uxxxx escapes for other characters.
   Function ‘tools::showNonASCIIfile’ can help in finding non-ASCII
```

and

```
checking Rd \usage sections ...
   Undocumented arguments in Rd file 'fsar_plot_base.Rd'
     ‘in.df’
   Documented arguments not in \usage in Rd file 'fsar_plot_base.Rd':
     ‘timeseries’
   
   Undocumented arguments in Rd file 'fsar_plot_ggplot.Rd'
     ‘df’
   Documented arguments not in \usage in Rd file 'fsar_plot_ggplot.Rd':
     ‘timeseries’
```

and

```
   > fsar_plot_ggplot(sim_fsar_data(format="wide"))
   Error in expansion(mult = c(0, 0.02)) : 
     could not find function "expansion"
```

and

```
 checking for portable file names ...
   Found the following files with non-portable file names:
     inst/csas-docx/FSAR FSRR Template-eng 231109.docx
     inst/csas-docx/FSAR FSRR Template-eng 231212.docx
     inst/csas-docx/FSAR FSRR Template-eng 240219.docx
     inst/csas-docx/P-AS P-RS Gabarit-fr 231109.docx
     inst/csas-docx/P-AS P-RS Gabarit-fr 240219.docx
   These are not fully portable file names.
```

**Comment by seananderson** [comment]
OK, the fsar branch is merged into the main branch. Note that I pulled the fsar plotting and simulation demo functions out of the package and into .R files within the fsar template folder. They would require a lot of package imports and are probably more useful as source code anyways. @PaulRegular @ricardd

**Comment by ricardd** [comment]
just some running notes as I am working on my Science Response (FSR)

- we should give the option to have a shorter report title to appear in the header of the rendered word document 
- the title page and context section keeps extraneous text that has to be manually removed from the rendered word document, how to improve this?
- how to best handle italics for latin names? using *latin name* in the title does not propagate to italicized text, it just add the asterisk to the title
- new to add csl to the index.Rmd template, so that references are formatted using the CSAS style
- how to format the list of participants to match CSAS requirements (adding bold_header=TRUE in csas_table doesn't work in the rendered word document)?
