### ISSUE TITLE
Word document title page template not found

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#29]
I guess that this template file should be in csasdown\inst\csas-docx, but it isn't. 

> csasdown::add_resdoc_titlepage()
Error: could not find file "templates/RES2016-eng-titlepage.docx"

**Comment by seananderson** [comment]
Here's the file https://github.com/pbs-assess/csasdown/blob/9c591fbd3569721d517e9928c82602c703d2e2ee/inst/rmarkdown/templates/resdoc/skeleton/templates/RES2016-eng-titlepage.docx

I forgot to bring that over when I switched away from the local templates folder. I was thinking of removing the function. The problem is that when the title page gets added it seems to get wrapped in a field code so that the Word document behaves strangely and can't be edited. We'd also have to change how you interact with this because if we put it in `inst/` then the user won't be able to edit the title page. Maybe it should go in the default file setup that gets created. 

Can you test the officer functions in here:

https://github.com/pbs-assess/csasdown/blob/d5641ce0a3179f42ba2fd4b08776791d9c1065a1/R/utils.R#L216-L221

and see if they create a usable document for you? The alternative is just to provide this file and suggest people copy and paste it at the beginning of their document when they are done.

**Comment by ricardd** [comment]
@seananderson this solution using officer works in that it adds a title page to the resulting Word document, but it is not filled in with the title, authors, etc.

**Comment by ricardd** [comment]
@seananderson , closing this, and I will edit the README.md file to describe how to deal with the title page in the Word document (i.e. 1) the function name changed from "add_resdoc_titlepage" to "add_resdoc_docx_titlepage", and 2) the title page appears in the templates folder and needs to be filled in manually and added to the final Word document).
