### ISSUE TITLE
Word issues: adding title page, page numbering, ...

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#32]
Working with @rollandn on this, we have rendered a Word document and wanted to document the issues we have encountered:

* when using the csasdown function add_resdoc_docx_titlepage(), the first page header is repeated in the whole document
* page numbers in the Word document are all in Roman numerals, even without adding a titlepage
* hyperlinks to citations are absolute paths
* cross-references to figures and tables are not maintained, so the figure and table numbers are correct, but it is not possible to add a List of Tables and a List of Figures

The list above is just meant to document the hurdles that we have encountered in producing our ResDoc, and to identify the issues that can possibly be solved in csasdown and those that are not within the scope of csasdown.

**Comment by seananderson** [comment]
There are limits to what is scriptable for .docx files. My guess is there's no way to fix the page numbers without tweaking it manually. I doubt there is a solution with the title page either other than manually pasting the title page yourself instead of using an R function or fixing the header yourself or removing the header from the joined title page template and then adding it back yourself after. If you figure out something else that works please let me know. The Word document will always need some level of final tweaking I think.

**Comment by ricardd** [comment]
Thanks @seananderson , I realise the limitations of producing Word documents. 

We would just send a PDF to the reviewers at this stage, but there are a number of wide tables that can't be properly displayed in the PDF (as per issue #31 ).

**Comment by ricardd** [comment]
@seananderson I still think that the need to produce a Word version at some stage in the review process will be appreciated by some. As such, perhaps we could use the wiki or elsewhere to document what can and can't be done with rendering a Word document instead of a PDF?

**Comment by seananderson** [comment]
The wiki sounds like a great place. Feel free to edit it and add sections. As that becomes more useful we can link to it from the README file.
