### ISSUE TITLE
SR error on \MakeAvailable

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#52]
Over here: https://github.com/pbs-assess/csasdown/issues/36#issuecomment-488745264
@ricardd notes that he can't run the SR unit test on the new template. It stops running at `\MakeAvailable`. I don't see anything wrong with that and it seems to build for me and Travis. Potentially a MikTeX related issue? Not sure.

**Comment by cgrandin** [comment]
@ricardd  - I fixed this yesterday. It was caused by a problem with how rdEmail is defined. It works properly now if you call `csasdown::draft("sr") ` but if you have an SR from before that's probably why it's breaking. Check the part about rdEmail in this commit and you can either fix your own manually or start again with `draft("sr") `:

8c08e554081aa14ab55e080de56025383be75a17

**Comment by cgrandin** [comment]
@ricardd The SR should be usable now. Did you get this working? Pull everything today and it should be good.
