### ISSUE TITLE
how to remove hyperlinks to figures and tables?

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#54]
It hurts me to ask, but it was requested by my regional CSAS office to only have hyperlinks in the navigation pane and in the Table of Contents, and not in references to Figures and Tables.

I have removed the hyperlinks to the citations by setting 'link-citations: false' in index.Rmd, but how to also disable links that appear in references to figures and tables? We use the LaTeX hyperref package in the style file, so perhaps it can be controlled there?

> S.v.p. enlever dans le texte les liens des citations, liens des tableaux et les liens des figures. Les seuls liens demandés, et qui sont conformes au gabarit du SCCS, sont ceux associés aux sections du rapport qui apparaissent dans la table des matières.

**Comment by seananderson** [comment]
Yes, the hyperef options. For now, you can just turn those off. Maybe we’ll make it an option later.

**Comment by cgrandin** [comment]
What possible motive could they have for doing this?

"Oh wait, I have a great idea! Let's make the document less navigable for everyone."
\-- CSAS

**Comment by seananderson** [comment]
Check that removing the citation links and the hyperref options doesn’t affect the bibliography finding regular expression (I.e. does it still get moved?) We might need to place a marker at the end of the .Rmd files to reliably find the start of the bibliography in that case.

**Comment by seananderson** [comment]
I can't figure out a way to do this. I read in various places that `ref*{}` should disable the link but that breaks the creation of the figure or table number for me. If that were to work then we could use a regular expression to add those throughout. Otherwise it seems like a one-shot deal. Either everything as hyperlinks or nothing has hyperlinks. The easiest way to turn off all hyperlinks is to add `draft` to the options passed to hyperref. If some regional offices insist on this and others do not then we could add this as an option. Surely we've published research documents with hyperlinked tables and figures before, no?
