### ISSUE TITLE
allow Appendices in Tech Report

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#65]
trying to add an Appendix to a Tech Report, not yet defined in the LaTeX style file

**Comment by obradovichs** [comment]
@cgrandin as we discussed re issues with preparation of our tech report for submission in mid-August prior to submission of a Res Doc in late August

We are having the same issue with appendices and had to create them as sections. We forced the section numbers to be letters, and gave figures alphanumeric identifiers, by modifying the code in the index.rmd, but this is just a patch and still doesn't operate correctly as an appendix.  

`# Any extra LaTeX code for the header:`
   
 `- \newcommand{\beginsupplementa}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}`

**Comment by seananderson** [comment]
See if what I did here works for you:
https://github.com/pbs-assess/csasdown/commit/063050598009bc4e35c940c29eed56218b75556c

Note that the command is `\\appendix` not `\\Appendices` like in Res Docs. The Tech Report style file was set up with the article class instead of the book class so everything is a bit different.

**Comment by obradovichs** [comment]
Thanks so much for this! It is close, probably just something small I am still learning. 

(1) If I don't include:  `\clearpage` at the top of the .Rmd for the appendix it runs underneath the figure section, which is different from the Res Docs.

(2) The following code:
`\clearpage`
`r if(knitr:::is_latex_output()) '\\appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

`# Data continuity in the Northern Abalone Database {#app:appA}`
`The Breen Survey Method for`

returns the title without the word Appendix in front of the appendix letter (note image is cropped)
![image](https://user-images.githubusercontent.com/45372441/61920159-827a4e80-af0d-11e9-977c-02f608270540.png)

I realized that all the appendices have to be in the same .Rmd file, but I am still not sure how to get appendix numbers like Figure A.1 etc. We had some code in our index that was forcing this to happen, but I had to remove it in order to get the tables to work.

**Comment by seananderson** [comment]
Try this: https://github.com/pbs-assess/csasdown/commit/ba88ae9fb8890a8e2217f91e2f46c0c96ca2c231

(Probably don't need `r if(knitr:::is_latex_output()) '\\unappendix'` now.)

You need `\clearpage` to tell LaTeX to stop all floats and start a new page. It's built into the Res Doc Appendices command.

Remove this part:

```
- \newcommand{\beginsupplementa}{\setcounter{table}{0} \renewcommand{\thetable}{A\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}
```

**Comment by obradovichs** [comment]
I pulled the changes to the csasdown repository, reinstalled the package, and changed our appendix .Rmd according to the example in the inst folder of the csasdown repository.

The figure/table numbering is still continued from the Figure section and we do not get the word appendix in the section titles.

Our code looks like:

`r if(knitr:::is_latex_output()) '% begin csasdown appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

 >\clearpage
`# Data continuity {#app:appA}`
Text 
Tables built from .csv files

>\clear page
`# Standardized index plots {#app:appB}`
Tables built with: csasdown::csas_table from stored objects
Figures called from stored png's:  `knitr::include_graphics(here::here("knitr-figs-pdf/a2fig1.png"))`

>\clear page
'# An example of the interaction {#app:appC}'
Figures built in section
Text

`r if(knitr:::is_latex_output()) '% end csasdown appendix'`



We do have a piece of code in our index.Rmd that tells knitr where to find the stored figures and how to size them, but as far as I can see there isn't anything in there that should affect numbering etc.
`knitr::opts_chunk$set`

**Comment by seananderson** [comment]
I just tweaked some things so that tables and equations will get renumbered, but it's working for me with the example:

![image](https://user-images.githubusercontent.com/19349/61979246-2ca6b480-afa8-11e9-8f64-6bdfc12e2377.png)

Can you see if the built-in example works for you?

Note that you should remove `\unappendix`: https://github.com/pbs-assess/csasdown/commit/7b6fd2e3d44f57cae8dbec693a311a57184b9b9f

Note that in your above example it should be `clearpage` not `clear page` (although that won't fix your main problem).

If it's working, then the output .tex in `_book/techreport.tex` from the example should look like this:

```tex
\begin{appendices}
\counterwithin{figure}{section}
\counterwithin{table}{section}
\counterwithin{equation}{section}

\clearpage

\label{app:first-appendix}
\section{THE FIRST APPENDIX}

Content here.
\begin{figure}[htb]

{\centering \pdftooltip{\includegraphics[width=6in]{knitr-figs-pdf/test1-1}}{Figure \ref{fig:test1}} 

}

\caption{Test}\label{fig:test1}
\end{figure}
\begin{longtable}[]{@{}lr@{}}
\caption{\label{tab:test2}Test}\tabularnewline
\toprule
x & y\tabularnewline
\midrule
\endfirsthead
\toprule
x & y\tabularnewline
\midrule
\endhead
a & 1\tabularnewline
a & 2\tabularnewline
b & 3\tabularnewline
\bottomrule
\end{longtable}
Figure~\ref{fig:test1}.

Table~\ref{tab:test2}.

\clearpage

\label{app:second-appendix}
\section{THE SECOND APPENDIX, FOR FUN}

More content.

\end{appendices}
                                           
```

**Comment by obradovichs** [comment]
Yes it works! Thanks again!
My version is almost the same as yours, except my figure appears on the next page. We are having the same problem with figures and tables in the Figures and Tables Sections.

I was able to copy in the text from our appendices, change the name of the appendices, add a table created from a .csv file, add a table created from an object, and add a figure called from a stored .png.

I'm now adding code in one chunk at a time to the new appendix.Rmd to see if breaks somewhere.

**Comment by obradovichs** [comment]
The figure counter works, but tables are still continuing on from the Tables section.

**Comment by seananderson** [comment]
Does the table numbering in the appendices work in the example?

The counters should be reset with the following code:

```
\begin{appendices}
\counterwithin{figure}{section}
\counterwithin{table}{section}
\counterwithin{equation}{section}
```

which should be injected into the .tex file in _book.

There likely needs to be a `\clearpage` first to stop the floating tables and figures.

If there is an example I can run, I can try to troubleshoot it.

**Comment by seananderson** [comment]
It's almost like you are a version behind, because initially I had only fixed the figure counter.

**Comment by obradovichs** [comment]
Yes, you're right. I'm sorry. I need to remind myself to git pull from csasdown more frequently, as you are making changes. I did notice that the `\counterwithin{table}{section}` was not in the version I was using.

Now our appendices look great!

**Comment by obradovichs** [comment]
Out of curiosity (if you can easily answer this), where is the counter for equations set for the main document? I tried looking in the tech-report.sty file and the .tex file in _book, as with the counter for the equations in the appendix.

**Comment by seananderson** [comment]
I don’t think they are explicitly set or reset anywhere besides in the appendix (which I haven’t actually tested). By default they start at 1 at the beginning of the document.

**Comment by obradovichs** [comment]
Our equations are numbered automatically in the tech report (main sections), but not in the tech report (main sections).

**Comment by obradovichs** [comment]
Appendices themselves are in great shape, but there appears to be a slight issue in referencing them. 

`Appendix \ref{app:first-appendix}, Tables \@ref(tab:COVvariablesummary)-\@ref(tab:algaecommunity)`

produces: Appendix 8, Tables A.1-A.14.

`Appendix \@ref(app:first-appendix)`

also produces the same: Appendix 8
We are using the {} style due to an issue with sec references. Remembered that I can attempt to fix these things and make a pull request, so will see if I can figure out.

**Comment by seananderson** [comment]
This should fix it: https://github.com/pbs-assess/csasdown/commit/1ed7d362d575d19bf293d9394fab9e15deb51aed
