### ISSUE TITLE
How do you get french to work..

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#77]
Doing the following in the index.Rmd file, I would expect french to work but it doesn't seem to:
```
output:
 csasdown::sr_pdf:
 french: true
```

For example, the tables are not labelled "Tableau 1., Tableau 2., etc" but remain labelled in English. I probably knew this at one point but it has slipped my mind

**Comment by ricardd** [comment]
@cgrandin, I believe that the full bilingual shakedown is only implemented for Research Documents.

I am working on a French Technical Report and was going to check all the details such as "Tableau" instead of "Table", etc.

I recall that most things are defined in the LaTeX style file, so perhaps there are some edits to do. Let me take a stab at this and see how far I get.

**Comment by ricardd** [comment]
OK, I modified things for the Technical Report, pending a merge after @seananderson reviews my commit.

e1fe2b801995311935eb250362d67d2ee6e52a2a

I will now try to tackle the Science Response.

**Comment by cgrandin** [comment]
I am indeed working on an SR so this will be great. Thanks @ricardd

**Comment by ricardd** [comment]
I just did a pull request with 2 commits, and will need assistance from @cgrandin and @seananderson
